import json
import os
from datetime import datetime

class ReportGenerator:
    def __init__(self, output_dir: str = "./report_template"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        
    def generate_markdown_report(self, asset_reg, threat_model, attack_paths, risk_eval, countermeasures) -> str:
        """
        Synthesizes the LLM pipeline outputs into a formatted Markdown TARA report.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report = f"# ISO/SAE 21434 TARA Report\n"
        report += f"**Generated:** {timestamp}\n\n"
        
        report += "## 1. Executive Summary\n"
        report += "This report compiles an automated Threat Analysis and Risk Assessment generated by the LLM-Powered Automotive Framework. Chain-of-Thought (CoT) reasoning and standard mappings (STRIDE, EVITA, CVSS, LINDDUN) were applied sequentially.\n\n"
        
        report += "## 2. Asset Register\n"
        report += "```json\n" + json.dumps(asset_reg, indent=2) + "\n```\n\n"
        
        report += "## 3. Threat Scenarios & Attack Paths\n"
        report += "```json\n" + json.dumps(threat_model, indent=2) + "\n```\n\n"
        
        report += "## 4. Risk Matrix (ISO 21434 & Privacy/LINDDUN)\n"
        report += "```json\n" + json.dumps(risk_eval, indent=2) + "\n```\n\n"
        
        report += "## 5. Mitigation Roadmap\n"
        report += "```json\n" + json.dumps(countermeasures, indent=2) + "\n```\n\n"
        
        file_path = os.path.join(self.output_dir, "Automated_TARA_Report.md")
        with open(file_path, "w") as f:
            f.write(report)
            
        return file_path
